### ISSUE TITLE
A super simple `has_property` or `has_molecule` method for a database.

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/atomlite#49]
to simplify this for the user:

```python
    def if_molecule_in_db(self, key: str) -> bool:
        entries = list(self._db.get_entries(key))
        if not entries:
            return True
        else:
            return False
```

**Comment by lukasturcani** [comment]
I would note that `has_property` is quite different to `has_molecule` and already addressed in: https://atomlite.readthedocs.io/en/latest/#checking-if-a-value-exists-in-the-database

**Comment by lukasturcani** [comment]
I'll add `has_entry` though

**Comment by andrewtarzia** [comment]
Yea i recognise that, but I figured it makes sense for the interface to have both 🙏🏻
